source "https://rubygems.org"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 8.0.2"
# Use postgres as the database for Active Record
gem "pg", "~> 1.5"

# Point to your gem (replace with the actual gemspec if different)
gem "mermaid_erd", path: "../.."

group :development, :test do
  gem "bootsnap", require: false
end
